export class TpCatSpecialVectors {

	tpCatSpecialVectorsId: any={ };
	tpModelHeaderId: string;
	specialVectorType: string;
	rateTable: string;
	daycntUnit: string;
	geogSpreadTable: string;
	tenor: string;
	month1: any={ };
	month2: any={ };
	month3: any={ };
	month4: any={ };
	month5: any={ };
	month6: any={ };
	month7: any={ };
	month8: any={ };
	month9: any={ };
	month10: any={ };
	month11: any={ };
	month12: any={ };
	month13: any={ };
	month14: any={ };
	month15: any={ };
	month16: any={ };
	month17: any={ };
	month18: any={ };
	month19: any={ };
	month20: any={ };
	month21: any={ };
	month22: any={ };
	month23: any={ };
	month24: any={ };
	month25: any={ };
	month26: any={ };
	month27: any={ };
	month28: any={ };
	month29: any={ };
	month30: any={ };
	month31: any={ };
	month32: any={ };
	month33: any={ };
	month34: any={ };
	month35: any={ };
	month36: any={ };
	month37: any={ };
	month38: any={ };
	month39: any={ };
	month40: any={ };
	month41: any={ };
	month42: any={ };
	month43: any={ };
	month44: any={ };
	month45: any={ };
	month46: any={ };
	month47: any={ };
	month48: any={ };
	month49: any={ };
	month50: any={ };
	month51: any={ };
	month52: any={ };
	month53: any={ };
	month54: any={ };
	month55: any={ };
	month56: any={ };
	month57: any={ };
	month58: any={ };
	month59: any={ };
	month60: any={ };
	createdBy: string;

}